FROM apache/airflow:2.5.1-python3.8

USER root
COPY setup.py /opt/airflow/setup.py
COPY src/ /opt/airflow/src/
RUN chown -R airflow: /opt/airflow
USER airflow
WORKDIR /opt/airflow
RUN pip install --no-cache-dir -e .
COPY dags/ /opt/airflow/dags
