version: "3.7"

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      redis:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/airflow.db"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      INPUT_CSV: /opt/airflow/data/novas_empresas.csv
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPARK_MASTER: local[2]
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "admin"
      _AIRFLOW_WWW_USER_PASSWORD: "admin"
      _AIRFLOW_WWW_USER_FIRSTNAME: "Admin"
      _AIRFLOW_WWW_USER_LASTNAME: "User"
      _AIRFLOW_WWW_USER_EMAIL: "admin@example.com"
      _AIRFLOW_WWW_USER_ROLE: "Admin"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: standalone

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/app
