FROM openjdk:17-slim

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY src/features/ /app/src/features/
COPY dags/ /app/dags/
COPY requirements.txt /app/
COPY tests/ /app/tests/

RUN pip3 install -e src/features/
RUN pip3 install -e dags/
RUN pip3 install -r requirements.txt

CMD ["pytest", "--maxfail=1", "--disable-warnings", "-q", "--cov=src", "--cov-report=term-missing"]
