FROM openjdk:17-slim

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY setup.py requirements.txt /app/
COPY src/ /app/src/
COPY tests/ /app/tests/

RUN pip3 install -r requirements.txt

CMD ["pytest"]
